"""Transparency label generator (planning.md §4).

The combined confidence score (P(AI)) is never shown raw to a reader — it is
mapped to exactly one of three plain-language label variants. This module is the
single source of truth for that text; the band edges are imported from
``scoring.py`` so the label can never disagree with the attribution that
``attribution_for()`` assigns (>=0.70 AI, <0.40 human, else uncertain).

The three strings below are verbatim from planning.md §4.
"""

from scoring import BAND_AI_MIN, BAND_HUMAN_MAX

LABEL_AI = (
    "🤖 **Likely AI-generated.** Our analysis found strong signals that this "
    "text was produced with AI assistance. This is an automated estimate, not a "
    "certainty — detection is imperfect. If you wrote this yourself, you can "
    "appeal this label."
)

LABEL_UNCERTAIN = (
    "❓ **Origin uncertain.** Our system couldn't confidently tell whether this "
    "was written by a person or generated by AI. Treat this as inconclusive — it "
    "is not a judgment either way. The creator can request a review."
)

LABEL_HUMAN = (
    "✍️ **Likely human-written.** Our analysis found strong signals consistent "
    "with human authorship. This is an automated estimate, not a guarantee."
)


def generate_label(confidence):
    """Map a combined confidence (or None) to one of three label variant strings.

    Mirrors the band logic of ``scoring.attribution_for``. ``None`` (both signals
    degraded → no confidence) is shown the hedged Uncertain label rather than any
    verdict, consistent with the false-positive asymmetry (planning.md §3).
    """
    if confidence is None:
        return LABEL_UNCERTAIN
    if confidence >= BAND_AI_MIN:
        return LABEL_AI
    if confidence < BAND_HUMAN_MAX:
        return LABEL_HUMAN
    return LABEL_UNCERTAIN
